from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.sql import func

from app.database import Base

# Pydantic
#    = API data

# SQLAlchemy
#    = Database data
# API request model
class ImageAttachment(BaseModel):
    """A single image sent inline with a chat message, base64-encoded."""
    filename: str
    mime_type: str
    data_base64: str


class ChatRequest(BaseModel):
    message: str
    conversation_id: str | None = None
    images: list[ImageAttachment] = []


# Database model
class Message(Base):

    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)

    conversation_id = Column(String, index=True)

    role = Column(String)

    content = Column(Text)

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )

class Conversation(Base):

    __tablename__ = "conversations"

    id = Column(String, primary_key=True, index=True)

    title = Column(String)

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )


class Image(Base):
    """An image attached to a message — either uploaded by the user (for
    the vision model to look at) or generated by the AI from a prompt.

    Stored as base64 text directly in the DB (no separate file storage),
    tied to the specific message it belongs to so it can be replayed in
    that exact turn when conversation history is rebuilt.
    """

    __tablename__ = "images"

    id = Column(Integer, primary_key=True, index=True)

    conversation_id = Column(String, index=True)

    message_id = Column(Integer, index=True)

    source = Column(String)  # "uploaded" or "generated"

    filename = Column(String)

    mime_type = Column(String)

    data_base64 = Column(Text)

    prompt = Column(Text, nullable=True)  # only set for source="generated"

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )


class Document(Base):
    """A file uploaded into a conversation, with its text already extracted.

    The extracted text (not the original file bytes) is what gets injected
    into the conversation's context, so we only ever store plain text here.
    """

    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)

    conversation_id = Column(String, index=True)

    filename = Column(String)

    content = Column(Text)

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )